name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.0', '8.1', '8.2', '8.3', '8.4' ]
      fail-fast: false

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          tools: composer-require-checker

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: composer run-script test

      - name: Run composer-require-checker
        run: composer-require-checker check

      - name: Install roave/backward-compatibility-check.
        run: composer require --dev roave/backward-compatibility-check

      - name: Run roave/backward-compatibility-check.
        run: vendor/bin/roave-backward-compatibility-check --format=github-actions
